# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PSBL
                                 A QGIS plugin
 This plugin creates editable pretty setback building lines
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-20
        copyright            : (C) 2024 by Bartosz Łęczycki
        email                : bartosz.leczycki98@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PSBL class from file PSBL.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .PBSL import PSBL
    return PSBL(iface)
